---
name: Conform Policies

on: [push, pull_request]

jobs:
  conform: # enforces policies on pipelines such as conventional commits.
    runs-on: ubuntu-latest
    name: Conform

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: siderolabs/conform@v0.1.0-alpha.30
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
